import { akasFor, getContact, getUser, linksFor, rosterFor, usesWorks, getWork } from '@/data/repo'
import type { Contribution } from '@/data/schema'
import { pct, workTypeLabel } from './format'

function proFields(c: Contribution): { pro: string; ipi: string; publisher: string; contact: string; legal: string } {
  const p = c.user_id ? getUser(c.user_id) : c.contact_id ? getContact(c.contact_id) : null
  return {
    pro: p?.pro_name ?? '',
    ipi: p?.pro_ipi ?? '',
    publisher: p?.publisher_name ?? '',
    contact: p?.contact_email ?? '',
    legal: p?.legal_name ?? '',
  }
}

export function buildCreditPackText(wid: string): string {
  const work = getWork(wid)
  if (!work) return ''
  const akas = akasFor(wid)
  const roster = rosterFor(wid)
  const uses = usesWorks(wid)
  const links = linksFor(wid)

  const lines: string[] = []
  lines.push(`CREDIT PACK — ${work.primary_title}`)
  lines.push(`Type: ${workTypeLabel[work.type]}`)
  if (akas.length) lines.push(`Also known as: ${akas.map((a) => a.title).join(' · ')}`)
  if (uses.length) lines.push(`Uses / based on: ${uses.map((u) => `${u.primary_title} (${workTypeLabel[u.type]})`).join(', ')}`)
  lines.push('')
  lines.push('ROSTER & SPLITS')
  for (const r of roster) {
    const f = proFields(r.contribution)
    const status =
      r.contribution.confirm_status === 'confirmed'
        ? 'confirmed'
        : r.contribution.confirm_status === 'awaiting_account'
          ? 'awaiting account'
          : 'pending'
    lines.push(`• ${r.name} — ${r.contribution.role} — ${pct(r.contribution.split_percent)} [${status}]`)
    const meta: string[] = []
    if (f.legal) meta.push(`Legal: ${f.legal}`)
    if (f.pro) meta.push(`PRO: ${f.pro}`)
    if (f.ipi) meta.push(`IPI/CAE: ${f.ipi}`)
    if (f.publisher) meta.push(`Publisher: ${f.publisher}`)
    if (f.contact) meta.push(`Contact: ${f.contact}`)
    if (meta.length) lines.push(`    ${meta.join(' | ')}`)
  }
  if (links.length) {
    lines.push('')
    lines.push('LINKS')
    for (const l of links) lines.push(`• ${l.label}: ${l.url}`)
  }
  lines.push('')
  lines.push(`Agreement status: ${work.agreement_status === 'confirmed' ? 'All splits agreed' : 'Change pending approval'}`)
  lines.push(`Generated by CoSign — collabs confirmed, credits clear.`)
  return lines.join('\n')
}
