import puppeteer from 'puppeteer'
const BASE = 'http://localhost:5173'
const b = await puppeteer.launch({ headless: true })
const p = await b.newPage()
await p.setCacheEnabled(false)
await p.setViewport({ width: 1180, height: 1000, deviceScaleFactor: 2 })
await p.goto(BASE, { waitUntil: 'networkidle0' })
await p.evaluate(() => localStorage.clear())
// first-run tour
await p.goto(BASE + '/app', { waitUntil: 'networkidle0' }); await new Promise(r=>setTimeout(r,400))
await p.screenshot({ path: '/tmp/e-tour.png' }); console.log('tour')
// dismiss tour, list view
await p.evaluate(() => { localStorage.setItem('cosign.tour.v1','1'); localStorage.setItem('cosign.library.view','list') })
await p.goto(BASE + '/app', { waitUntil: 'networkidle0' }); await new Promise(r=>setTimeout(r,300))
await p.screenshot({ path: '/tmp/e-library-list.png' }); console.log('library-list')
// grid view
await p.evaluate(() => localStorage.setItem('cosign.library.view','grid'))
await p.goto(BASE + '/app', { waitUntil: 'networkidle0' }); await new Promise(r=>setTimeout(r,300))
await p.screenshot({ path: '/tmp/e-library-grid.png' }); console.log('library-grid')
// work detail (No Ceilings, pending approval)
await p.goto(BASE + '/app', { waitUntil: 'networkidle0' })
await p.evaluate(() => { const el=[...document.querySelectorAll('button')].find(e=>e.innerText.includes('No Ceilings')); el&&el.click() })
await new Promise(r=>setTimeout(r,500)); await p.screenshot({ path: '/tmp/e-work.png' }); console.log('work')
// propose modal (open Velvet Static → Propose a change)
await p.goto(BASE + '/app', { waitUntil: 'networkidle0' })
await p.evaluate(() => { const el=[...document.querySelectorAll('button')].find(e=>e.innerText.includes('Velvet Static') && !e.innerText.includes('Type Beat')); el&&el.click() })
await new Promise(r=>setTimeout(r,400))
await p.evaluate(() => { const el=[...document.querySelectorAll('button')].find(e=>e.innerText.includes('Propose a change')); el&&el.click() })
await new Promise(r=>setTimeout(r,400)); await p.screenshot({ path: '/tmp/e-propose.png' }); console.log('propose')
await b.close()
